### ISSUE TITLE
Is there a way to change visualizer options?

### ISSUE THREAD

**Issue by wvffle** [korbav/wave.js-typescript#1]
I'm not that familiar with typescript. Is there a way to change visualizer options?

I want to close the rendered path.

**Comment by korbav** [comment]
Are you talking of a visual effect that you would like to alter?
If so, there's no parameter to achieve that for the moment, effects come indeed as they are and the only thing you can modify is the stroke width & the colors.

**Comment by wvffle** [comment]
I'm talking about `IVisualizerOptions`. I wanted to simply have a wave filled with color. I guess I'll just use what's available then. Thanks!
